[package]
name = "neo-ideas"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
axum = "0.7.5"
tokio = { version = "1.38.0", features = ["full"] }
